server:
  port: 8765



spring:
  application:
    name: provider-news
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/math?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/1809a
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 500


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
